apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cockroach-operator.fullname" . }}-sa
  labels:
    app: cockroach-operator
  {{- include "cockroach-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sa.serviceAccount.annotations | nindent 4 }}