apiVersion: v1
kind: Service
metadata:
  name: cockroach-operator-webhook-service
  labels:
    control-plane: cockroach-operator
  {{- include "cockroach-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app: cockroach-operator
  {{- include "cockroach-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 }}
